const FONT_WEIGHT_OPTIONS = [
  'normal',
  'bold',
  'bolder',
  'lighter',
  '100',
  '200',
  '300',
  '400',
  '500',
  '600',
  '700',
  '800',
  '900',
]
const BASE_TEXTSTYLE_CONF = [
  { key: 'color', type: 'string', comp: 'color' },
  { key: 'fontStyle', type: 'string', comp: 'select', options: ['normal', 'italic', 'oblique'] },
  { key: 'fontWeight', type: 'string', comp: 'select', options: FONT_WEIGHT_OPTIONS },
  { key: 'fontFamily', type: 'string', comp: 'input' },
  { key: 'fontSize', type: 'number', comp: 'input' },
  { key: 'lineHeight', type: 'number', comp: 'input' },
  { key: 'width', type: 'number', comp: 'input' },
  { key: 'height', type: 'number', comp: 'input' },
  { key: 'textBorderColor', type: 'string', comp: 'color' },
  { key: 'textBorderWidth', type: 'string', comp: 'input' },
  { key: 'textBorderType', type: 'string', comp: 'input' },
  { key: 'textBorderDashOffset', type: 'number', comp: 'input' },
  { key: 'textShadowColor', type: 'string', comp: 'color' },
  { key: 'textShadowBlur', type: 'number', comp: 'input' },
  { key: 'textShadowOffsetX', type: 'number', comp: 'input' },
  { key: 'textShadowOffsetY', type: 'number', comp: 'input' },
  { key: 'overflow', type: 'string', comp: 'select', options: ['truncate', 'break', 'breakAll'] },
  { key: 'ellipsis', type: 'string', comp: 'input' },
]
export const BASE_OPTIONS_TITLE = [
  { key: 'id', type: 'string', comp: 'input', tips: '组件 ID。默认不指定。指定则可用于在 option 或者 API 中引用组件。' },
  { key: 'show', type: 'boolean', comp: 'switch' },
  { key: 'text', type: 'string', comp: 'input' },
  { key: 'link', type: 'string', comp: 'input' },
  { key: 'target', type: 'string', comp: 'select' },
  {
    key: 'textStyle',
    type: 'p', child: BASE_TEXTSTYLE_CONF
  },
  { key: 'subtext', type: 'string', comp: 'input' },
  { key: 'sublink', type: 'string', comp: 'input' },
  { key: 'subtarget', type: 'string', comp: 'select', options: ['self', 'blank'] },
  {
    key: 'subtextStyle',
    type: 'p', child: BASE_TEXTSTYLE_CONF
  },
  { key: 'textAlign', type: 'string', comp: 'select', options: ['auto', 'left', 'right', 'center'] },
  { key: 'textVerticalAlign', type: 'string', comp: 'select', options: ['auto', 'top', 'bottom', 'middle'] },
  { key: 'triggerEvent', type: 'boolean', comp: 'switch' },
  {
    key: 'padding',
    type: ['number', 'array'], comp: 'input',
  },
  { key: 'itemGap', type: 'number', comp: 'input' },
  { key: 'zlevel', type: 'number', comp: 'input' },
  { key: 'z', type: 'number', comp: 'input' },
  { key: 'left', type: ['string', 'number'], comp: 'input' },
  { key: 'top', type: ['string', 'number'], comp: 'input' },
  { key: 'right', type: ['string', 'number'], comp: 'input' },
  { key: 'bottom', type: ['string', 'number'], comp: 'input' },
  { key: 'backgroundColor', type: 'string', comp: 'color' },
  { key: 'borderColor', type: 'string', comp: 'color' },
  { key: 'borderWidth', type: 'string', comp: 'input' },
  {
    key: 'borderRadius',
    type: ['number', 'array'],
    comp: 'input',
  },
  { key: 'shadowBlur', type: 'number', comp: 'input' },
  { key: 'shadowColor', type: 'string', comp: 'color' },
  { key: 'shadowOffsetX', type: 'number', comp: 'input' },
  { key: 'shadowOffsetY', type: 'number', comp: 'input', tips: '阴影垂直方向上的偏移距离' },
]
export const CONF = [{ key: 'title', type: 'p', child: BASE_OPTIONS_TITLE }]