const FONT_WEIGHT_OPTIONS = [
  'normal',
  'bold',
  'bolder',
  'lighter',
  '100',
  '200',
  '300',
  '400',
  '500',
  '600',
  '700',
  '800',
  '900',
]
const BASE_TEXTSTYLE_CONF = [
  { key: 'color', type: 'string', comp: 'color', tips: '文字颜色，支持十六进制、rgb 或渐变' },
  { key: 'fontStyle', type: 'string', comp: 'select', options: ['normal', 'italic', 'oblique'], tips: '字体风格：normal 正常 / italic 斜体 / oblique 倾斜（多数浏览器与 italic 无差异）' },
  { key: 'fontWeight', type: 'string', comp: 'select', options: FONT_WEIGHT_OPTIONS, tips: '字体粗细，可选 normal、bold 或 100-900' },
  { key: 'fontFamily', type: 'string', comp: 'input', tips: '字体名称，如 Arial, sans-serif' },
  { key: 'fontSize', type: 'number', comp: 'input', default: 12, tips: '文字大小（像素）' },
  { key: 'lineHeight', type: 'number', comp: 'input', tips: '文字行高（像素）' },
  { key: 'width', type: 'number', comp: 'input', tips: '文本块宽度，超出后按 overflow 策略处理' },
  { key: 'height', type: 'number', comp: 'input', tips: '文本块高度，超出后按 overflow 策略处理' },
  { key: 'textBorderColor', type: 'string', comp: 'color', tips: '文字描边颜色' },
  { key: 'textBorderWidth', type: 'string', comp: 'input', tips: '文字描边宽度（像素）' },
  { key: 'textBorderType', type: 'string', comp: 'input', tips: '文字描边类型：solid 实线 / dotted 点线 / dashed 虚线' },
  { key: 'textBorderDashOffset', type: 'number', comp: 'input', tips: '虚线描边的起始偏移量' },
  { key: 'textShadowColor', type: 'string', comp: 'color', tips: '文字阴影颜色' },
  { key: 'textShadowBlur', type: 'number', comp: 'input', tips: '文字阴影模糊大小' },
  { key: 'textShadowOffsetX', type: 'number', comp: 'input', tips: '文字阴影水平方向偏移距离' },
  { key: 'textShadowOffsetY', type: 'number', comp: 'input', tips: '文字阴影垂直方向偏移距离' },
  { key: 'overflow', type: 'string', comp: 'select', options: ['truncate', 'break', 'breakAll'], tips: '超出宽高处理：truncate 截断 / break 按单词换行 / breakAll 强制换行' },
  { key: 'ellipsis', type: 'string', comp: 'input', tips: '截断时显示的省略符号，默认 ...' },
]
export const BASE_OPTIONS_TITLE = [
  { key: 'id', type: 'string', comp: 'input', tips: '组件 ID。默认不指定。指定则可用于在 option 或者 API 中引用组件。' },
  { key: 'show', type: 'boolean', comp: 'switch', tips: '是否显示标题组件' },
  { key: 'text', type: 'string', comp: 'input', tips: '主标题文本，支持 \n 换行' },
  { key: 'link', type: 'string', comp: 'input', tips: '主标题文本超链接地址' },
  { key: 'target', type: 'string', comp: 'select', options: ['self', 'blank'], tips: '超链接打开方式：self 当前窗口 / blank 新窗口' },
  {
    key: 'textStyle',
    type: 'p', child: BASE_TEXTSTYLE_CONF, tips: '主标题文本样式'
  },
  { key: 'subtext', type: 'string', comp: 'input', tips: '副标题文本，支持 \n 换行' },
  { key: 'sublink', type: 'string', comp: 'input', tips: '副标题文本超链接地址' },
  { key: 'subtarget', type: 'string', comp: 'select', options: ['self', 'blank'], tips: '副标题超链接打开方式：self 当前窗口 / blank 新窗口' },
  {
    key: 'subtextStyle',
    type: 'p', child: BASE_TEXTSTYLE_CONF, tips: '副标题文本样式'
  },
  { key: 'textAlign', type: 'string', comp: 'select', options: ['auto', 'left', 'right', 'center'], tips: '整个标题组件（含主副标题）相对定位位置的水平对齐' },
  { key: 'textVerticalAlign', type: 'string', comp: 'select', options: ['auto', 'top', 'bottom', 'middle'], tips: '整个标题组件（含主副标题）相对定位位置的垂直对齐' },
  { key: 'triggerEvent', type: 'boolean', comp: 'switch', tips: '是否触发鼠标事件，开启后可监听标题点击' },
  {
    key: 'padding',
    type: ['number', 'array'], comp: 'input', tips: '内边距，数字或数组 [上下, 左右]，如 [5, 10]'
  },
  { key: 'itemGap', type: 'number', comp: 'input', default: 10, tips: '主标题和副标题之间的间距（像素）' },
  { key: 'zlevel', type: 'number', comp: 'input', tips: 'canvas 层级，值越大越靠上；不同 zlevel 使用独立 canvas' },
  { key: 'z', type: 'number', comp: 'input', tips: '同一 zlevel 内的显示顺序，值大者在上' },
  { key: 'left', type: ['string', 'number'], comp: 'input', tips: '组件距离容器左侧的距离，如 0、center、10%' },
  { key: 'top', type: ['string', 'number'], comp: 'input', tips: '组件距离容器顶部的距离，如 0、top、10%' },
  { key: 'right', type: ['string', 'number'], comp: 'input', tips: '组件距离容器右侧的距离，如 0、10%' },
  { key: 'bottom', type: ['string', 'number'], comp: 'input', tips: '组件距离容器底部的距离，如 0、10%' },
  { key: 'backgroundColor', type: 'string', comp: 'color', tips: '标题背景颜色，支持透明或渐变' },
  { key: 'borderColor', type: 'string', comp: 'color', tips: '标题边框颜色' },
  { key: 'borderWidth', type: 'string', comp: 'input', tips: '标题边框宽度（像素）' },
  {
    key: 'borderRadius',
    type: ['number', 'array'],
    comp: 'input', tips: '边框圆角半径，数字或数组分别设置四个角',
  },
  { key: 'shadowBlur', type: 'number', comp: 'input', tips: '阴影模糊大小' },
  { key: 'shadowColor', type: 'string', comp: 'color', tips: '阴影颜色' },
  { key: 'shadowOffsetX', type: 'number', comp: 'input', tips: '阴影水平方向上的偏移距离' },
  { key: 'shadowOffsetY', type: 'number', comp: 'input', tips: '阴影垂直方向上的偏移距离' },
]
export const BASE_OPTIONS_AXIS = [
  { key: 'show', type: 'boolean', comp: 'switch', tips: '是否显示该坐标轴' },
  { key: 'name', type: 'string', comp: 'input', tips: '坐标轴名称，显示在轴的两端' },
  { key: 'nameGap', type: 'number', comp: 'input', default: 15, tips: '坐标轴名称与轴线之间的距离' },
  { key: 'inverse', type: 'boolean', comp: 'switch', tips: '是否反向展示坐标轴' },
  { key: 'position', type: 'string', comp: 'select', options: ['top', 'bottom', 'left', 'right'], tips: '坐标轴位置' },
  { key: 'axisLine.show', type: 'boolean', comp: 'switch', tips: '是否显示坐标轴轴线' },
  { key: 'axisTick.show', type: 'boolean', comp: 'switch', tips: '是否显示坐标轴刻度' },
  { key: 'axisLabel.show', type: 'boolean', comp: 'switch', tips: '是否显示坐标轴刻度标签' },
  { key: 'axisLabel.rotate', type: 'number', comp: 'input', default: 0, tips: '刻度标签旋转角度，-90 到 90' },
  { key: 'splitLine.show', type: 'boolean', comp: 'switch', tips: '是否显示分隔线（网格线）' },
  { key: 'splitArea.show', type: 'boolean', comp: 'switch', tips: '是否显示分隔区域' },
]
export const BASE_OPTIONS_XAXIS = [
  { key: 'type', type: 'string', comp: 'select', options: ['category', 'value', 'time', 'log'], tips: '坐标轴类型：category 类目轴 / value 数值轴 / time 时间轴 / log 对数轴' },
  { key: 'data', type: ['array'], comp: 'input', default: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'], tips: '类目数据，仅 category 轴生效，如 ["Mon","Tue"]' },
  ...BASE_OPTIONS_AXIS,
]
export const BASE_OPTIONS_YAXIS = [
  { key: 'type', type: 'string', comp: 'select', options: ['value', 'category', 'time', 'log'], tips: '坐标轴类型：value 数值轴 / category 类目轴 / time 时间轴 / log 对数轴' },
  { key: 'min', type: ['number', 'string'], comp: 'input', tips: '坐标轴最小值，可填数字或 dataMin' },
  { key: 'max', type: ['number', 'string'], comp: 'input', tips: '坐标轴最大值，可填数字或 dataMax' },
  ...BASE_OPTIONS_AXIS,
]
export const BASE_OPTIONS_SERIES = [
  { key: 'type', type: 'string', comp: 'select', options: ['line', 'bar', 'pie', 'scatter'], tips: '系列类型：line 折线 / bar 柱状 / pie 饼图 / scatter 散点' },
  { key: 'name', type: 'string', comp: 'input', tips: '系列名称，用于图例和提示框显示' },
  { key: 'stack', type: 'string', comp: 'input', tips: '堆叠标识，相同 stack 的系列会堆叠' },
  { key: 'smooth', type: 'boolean', comp: 'switch', tips: '折线是否平滑显示（仅 line 有效）' },
  { key: 'symbolSize', type: 'number', comp: 'input', default: 10, tips: '标记图形大小（仅 line/scatter 有效）' },
  { key: 'colorBy', type: 'string', comp: 'select', options: ['series', 'data'], tips: '颜色分配方式：按系列或按数据项（仅 pie 有效）' },
  { key: 'label.show', type: 'boolean', comp: 'switch', tips: '是否显示系列图形上的标签' },
  { key: 'itemStyle.color', type: 'string', comp: 'color', tips: '图形元素的颜色' },
  { key: 'itemStyle.borderRadius', type: 'number', comp: 'input', default: 4, tips: '图形元素圆角半径（bar/pie 有效）' },
  { key: 'data', type: ['array'], comp: 'input', default: [150, 230, 224, 218, 135, 147, 260], tips: '系列数据数组，如 [150, 230, 224]' },
]
export const CONF = [
  { key: 'title', type: 'p', child: BASE_OPTIONS_TITLE, tips: '标题组件，包含主标题和副标题' },
  { key: 'xAxis', type: 'p', child: BASE_OPTIONS_XAXIS, tips: 'X 轴（直角坐标系横轴）配置' },
  { key: 'yAxis', type: 'p', child: BASE_OPTIONS_YAXIS, tips: 'Y 轴（直角坐标系纵轴）配置' },
  { key: 'series', type: 'p', child: BASE_OPTIONS_SERIES, tips: '系列列表，每个系列通过 type 决定图表类型' },
]
