export const defaultCollectionList = [
  {
    type: 'function',
    icon: '',
    title: '万年历',
    value: 'Date',
    href: '',
  },
  {
    type: 'function',
    icon: '../../../../../public/media/image/icon/z23_2.png',
    title: '六爻',
    value: 'Hexagram',
    href: '',
  },
  // {
  //   type: 'function',
  //   icon: '../../../../../public/media/image/icon/z23_2.png',
  //   title: 'Azurlane',
  //   value: 'StatisticsSpace',
  //   href: '',
  // },
  {
    type: 'link',
    icon: 'https://fgo.wiki/favicon.ico',
    href: 'https://fgo.wiki/w/%E9%A6%96%E9%A1%B5',
    title: 'fgo-wiki',
    value: 'link-fgo',
  },
  {
    type: 'link',
    icon: 'https://static.hdslb.com/images/favicon.ico',
    href: 'https://wiki.biligame.com/blhx/%E9%A6%96%E9%A1%B5',
    title: 'AL wiki',
    value: 'link-azur',
  },
  {
    type: 'link',
    icon: 'https://github.githubassets.com/favicons/favicon.svg',
    href: 'https://github.com/',
    title: 'Github',
    value: 'link-github',
  },
  {
    type: 'link',
    icon: 'https://threejs.org/files/favicon.ico',
    href: 'https://threejs.org/docs/index.html#manual/zh/introduction/Creating-a-scene',
    title: 'ThreeJs',
    value: 'link-three',
  },
  {
    type: 'link',
    icon: 'https://pixijs.io/guides/static/images/pixijs-logo.svg',
    href: 'https://pixijs.download/release/docs/index.html',
    title: 'PixiJS',
    value: 'link-pixijs',
  },
  {
    type: 'link',
    icon: 'https://mdn.alipayobjects.com/huamei_qa8qxu/afts/img/A*7svFR6wkPMoAAAAAAAAAAAAADmJ7AQ/original',
    href: 'https://antv.vision/zh/',
    title: 'antV',
    value: 'link-antV',
  },
  {
    type: 'link',
    icon: 'https://es6.ruanyifeng.com/favicon.ico',
    href: 'https://es6.ruanyifeng.com/',
    title: 'ES6',
    value: 'link-es6',
  },
  {
    type: 'link',
    icon: 'https://www.smashingmagazine.com/images/favicon/favicon.svg',
    href: 'https://www.smashingmagazine.com/',
    title: 'S & M',
    value: 'link-sm',
  },
];